name: CD - Release to npm

on:
  push:
    branches: [main]

jobs:
  release:
    name: Build, Test and Publish to npm
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: 1.1.38
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          registry-url: 'https://registry.npmjs.org'
      
      - name: Install dependencies
        run: bun install --frozen-lockfile
      
      - name: Run linter
        run: bun run lint
      
      - name: Build project
        run: bun run build
      
      - name: Run tests
        run: bun run test
      
      - name: Verify dist output
        run: |
          if [ ! -d "dist" ]; then
            echo "Error: dist directory not created"
            exit 1
          fi
          if [ ! -f "dist/index.js" ]; then
            echo "Error: dist/index.js not found"
            exit 1
          fi
          if [ ! -f "dist/index.cjs" ]; then
            echo "Error: dist/index.cjs not found"
            exit 1
          fi
          if [ ! -f "dist/cli.cjs" ]; then
            echo "Error: dist/cli.cjs not found"
            exit 1
          fi
          echo "✅ Build artifacts verified"
      
      - name: Check npm configuration
        run: |
          echo "📦 Package name: $(npm pkg get name | tr -d '"')"
          echo "📦 Package version: $(npm pkg get version | tr -d '"')"
          echo "📦 Registry: https://registry.npmjs.org"
      
      - name: Publish to npm
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}