name: CI

on:
  push:
    branches: [develop]
  pull_request:
    branches: [develop]

jobs:
  test:
    name: Build and Test
    runs-on: ubuntu-latest

    strategy:
      matrix:
        bun-version: [1.1.38]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install zowe
        run: sudo apt-get update && sudo apt-get install -y build-essential libsecret-1-dev

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: ${{ matrix.bun-version }}

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Run linter
        run: bun run lint

      - name: Build project
        run: bun run build

      - name: Run tests
        run: bun run test

      - name: Verify dist output
        run: |
          if [ ! -d "dist" ]; then
            echo "Error: dist directory not created"
            exit 1
          fi
          if [ ! -f "dist/index.js" ]; then
            echo "Error: dist/index.js not found"
            exit 1
          fi
          if [ ! -f "dist/index.cjs" ]; then
            echo "Error: dist/index.cjs not found"
            exit 1
          fi
          if [ ! -f "dist/cli.cjs" ]; then
            echo "Error: dist/cli.cjs not found"
            exit 1
          fi
          echo "✅ Build artifacts verified"
